//! The tray icon, its menu, and the two ways back to a window that is not on screen.
//!
//! Desktop only: a phone has no tray, and this module is not in the mobile binary.
//!
//! This is what makes closing the window something other than quitting. With a tray there the
//! application goes on running with nothing on screen, so this module is also where a person
//! ends it — and [`installed`] is what the window asks before it dares hide, because an
//! application that hides with no tray to come back from is one somebody has lost.
//!
//! **The menu is named by the frontend.** Its entries are text a person reads, and only that
//! side holds the catalogs (`.agents/rules/user-facing-text.md`), so [`install`] is a command
//! rather than a call made at startup: the interface loads, looks its labels up, and hands
//! them here. It is named `install_tray` rather than `install` because a command's name is
//! flat across the whole application: the module in front of it is this side's, not the
//! interface's.

use log::{info, warn};
use tauri::{
    AppHandle,
    menu::{Menu, MenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
};

use crate::window;

/// Identifier of the tray icon, so that it can be asked for rather than remembered.
const TRAY: &str = "main";

/// Identifier of the menu entry that ends the application.
const QUIT: &str = "quit";

/// The glyph a tray draws, and it is not the same file on every platform.
///
/// Both are generated by `task icons` from one piece of artwork. macOS is handed the bare mark
/// as a template image and tints it to whatever its bar is doing, light or dark; a coloured
/// icon handed to it is drawn as a flat square. Windows and Linux do not tint, so they get the
/// reversed glyph, which is the one that reads on the dark bars both tend to have.
#[cfg(target_os = "macos")]
const GLYPH: &[u8] = include_bytes!("../icons/tray.png");
#[cfg(not(target_os = "macos"))]
const GLYPH: &[u8] = include_bytes!("../icons/trayNegative.png");

/// Whether the tray icon is on the bar.
///
/// The window asks this before hiding instead of closing. If the tray failed to build, hiding
/// would put the application somewhere with no way back on this screen, so the window closes
/// the ordinary way instead and the application ends with it.
pub fn installed(app: &AppHandle) -> bool {
    app.tray_by_id(TRAY).is_some()
}

/// Puts the tray icon on the bar, with a menu holding the entry it was handed.
///
/// `quit` is the name of the one entry, already translated by the caller — this side has no
/// catalogs to translate it from.
///
/// Called again — by a webview that reloaded, which in development happens on every save — it
/// does nothing and says so in the log. One tray, not one per reload.
///
/// A failure is written to the log and goes no further. There is nothing the interface could
/// do about it and nothing it could usefully say, and [`installed`] is what keeps the failure
/// from costing anybody their window.
#[tauri::command]
pub fn install_tray(app: AppHandle, quit: String) {
    if installed(&app) {
        info!("tray_already_installed");
        return;
    }

    if let Err(error) = build(&app, &quit) {
        warn!("tray_not_installed reason={error}");
        return;
    }

    info!("tray_installed");
}

/// Builds the icon and the menu, and hangs both behaviours off it.
///
/// # Errors
///
/// Returns whatever Tauri raised: the glyph not decoding, the menu not building, or the
/// platform refusing a tray icon — on Linux, most often because nothing on the desktop is
/// serving one.
fn build(app: &AppHandle, quit: &str) -> tauri::Result<()> {
    let quit_item = MenuItem::with_id(app, QUIT, quit, true, None::<&str>)?;
    let menu = Menu::with_items(app, &[&quit_item])?;

    TrayIconBuilder::with_id(TRAY)
        .icon(tauri::image::Image::from_bytes(GLYPH)?)
        .icon_as_template(cfg!(target_os = "macos"))
        .menu(&menu)
        // The left button is the way back to the window, so it must not be spent opening the
        // menu as well. The menu stays on the right button, where every platform puts it.
        .show_menu_on_left_click(false)
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                window::show_main(tray.app_handle());
            }
        })
        .on_menu_event(|app, event| {
            if event.id() == QUIT {
                info!("quit_from_tray");
                app.exit(0);
            }
        })
        .build(app)?;

    Ok(())
}
